mongoose:
  host: localhost
  port: 27017
  database: chatbot

account:
  username: EMAIL/PHONE
  password: PASSWORD
  state: /data/chatbot/state.json

bot:
  trigger: "run"
  name:
    full: Full Bot Name
    nick: Bot
  id: 000000000000000
  admin:
    - 000000000000000

handlers:
  - MessageStoreHandler
  - CommandHandler
  - EasterEggHandler

login:
  logLevel: warn
  selfListen: false
  listenEvents: false
  pageID: ''
  updatePresence: false
  forceLogin: false
  timeout: 30

commands:
  ChangeEmoji:
    enabled: true

eggs:
  - SuicidePrevention

    