mongoose:
  host: mongo
  port: 27017
  database: bot
account:
  username: email
  password: password
  state: /data/app/state.json
bot:
  trigger: run
  name:
    full: Firstname Middlename Surname
    nick: First
  id: 0000000000
  admin:
    - 0000000000
login:
  logLevel: warn
  selfListen: false
  listenEvents: false
  pageID: ''
  updatePresence: false
  forceLogin: false
  timeout: 30
reddit:
  client: client
  secret: secret
  username: username
  password: password
handlers:
  - MessageStoreHandler
  - CommandHandler
  - EasterEggHandler
commands:
  TestCommand:
    enabled: true
eggs:
  - Ping
  - DankMeme
crons:
  - WednesdayFrog
cronsubs: []
fmf:
  user: username
  pass: password
  users:
    icloudUserID: NameToShow
    iCloudUserID2: NameToShow
gaming:
  users:
    user1:
      discord: 'id'
      steam: 'id'
discord:
  id: 'id'
  secret: 'secret'
  token: 'bottoken'
